Repository openshift/operator-custom-metrics, pull requests merged in 2019-07, with the labels that each got.

#1 [init] Remove operator specific code
  go.mod
  go.sum
  pkg/metrics/builder.go
  pkg/metrics/metrics.go
  pkg/metrics/metricsconfig.go
  pkg/metrics/service.go
Labels: size/XL

#5 Get current route on update, and use resourceVersions
  pkg/metrics/service.go
Labels: size/S

#7 Fixed the command to get the package
  README.md
Labels: size/XS

#9 [fix] Improve builder to include adding list of metrics
  README.md
  go.sum
  pkg/metrics/builder.go
  pkg/metrics/metrics.go
  pkg/metrics/metricsconfig.go
  pkg/metrics/service.go
Labels: lgtm, size/M
